"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { ArrowLeft, Check, MessageSquare, X } from "lucide-react";
import Header from "@/components/layout/Header";
import DashboardSidebar from "@/components/dashboard/DashboardSidebar";
import AgentAuthProvider from "@/components/auth/AgentAuthProvider";
import { useSocket } from "@/providers/SocketProvider";
import { purchaseOrderApi } from "@/services/purchase-order.service";
import { formatPrice } from "@/lib/utils";
import { ConversationEventCard } from "@/components/wholesale/conversation";
import type { PurchaseOrder } from "@/types/wholesale";

export default function PurchaseOrderDetailPage() {
 const { id } = useParams<{ id: string }>(); const { subscribe } = useSocket(); const [po, setPo] = useState<PurchaseOrder | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [reason, setReason] = useState(""); const [reference, setReference] = useState(""); const [method, setMethod] = useState<"CARD"|"CASH"|"E_WALLET">("E_WALLET"); const [address, setAddress] = useState(""); const [date, setDate] = useState(""); const [message, setMessage] = useState(""); const [showReceipt, setShowReceipt] = useState(false);
 const load = useCallback(async () => { try { const next = await purchaseOrderApi.get(id); setPo(next); setAddress(next.delivery?.address ?? ""); setDate(next.delivery?.scheduledDate?.slice(0, 10) ?? ""); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load this purchase order."); } }, [id]);
 useEffect(() => { void load(); }, [load]); useEffect(() => subscribe(({ event, payload }) => { if (event.startsWith("purchaseOrder:") && (!payload?.poId || payload.poId === id)) void load(); }), [subscribe, id, load]);
 const action = async (fn: () => Promise<PurchaseOrder>) => { setBusy(true); setError(null); try { setPo(await fn()); } catch (e) { setError(e instanceof Error ? e.message : "Action failed."); } finally { setBusy(false); } };
 if (!po) return <AgentAuthProvider><main className="min-h-screen bg-[#f7f7f5]"><Header wholesale /><div className="p-10 text-center text-slate-500">{error ?? "Loading purchase order…"}</div></main></AgentAuthProvider>;
 const subtotal = po.lineItems.reduce((sum, item) => sum + item.subtotal, 0);
 return <AgentAuthProvider><main className="min-h-screen bg-[#f7f7f5]"><Header wholesale /><div className="flex"><DashboardSidebar /><div className="flex-1"><div className="container-shell py-8"><Link href="/wholesale/orders" className="mb-5 inline-flex items-center gap-2 text-sm text-slate-600"><ArrowLeft className="size-4" />Purchase Orders</Link>{error && <div className="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}
  <div className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-bold">{po.poNumber}</h1><p className="mt-1 text-slate-600">{po.supplier?.name ?? "Supplier"} · Created {new Date(po.createdAt).toLocaleDateString("en-PH", { dateStyle: "long" })}</p></div><div className="rounded-full bg-slate-100 px-3 py-1.5 text-sm font-medium">{po.status} · Payment {po.paymentStatus}</div></div>
  <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_22rem]"><div className="space-y-6"><section className="rounded-xl border border-slate-100 bg-white p-5"><h2 className="font-semibold">Order summary</h2><div className="mt-4 divide-y">{po.lineItems.map(item => <div key={item.id} className="flex gap-4 py-4"><div className="flex size-12 shrink-0 items-center justify-center overflow-hidden rounded-lg bg-slate-100">{item.supplierItem.image ? <img className="h-full w-full object-cover" src={item.supplierItem.image} alt="" /> : ""}</div><div className="min-w-0 flex-1"><p className="font-medium">{item.itemName || item.supplierItem.name}</p><p className="text-xs text-slate-500">{item.itemSku || item.supplierItem.sku || "No SKU"}</p><p className="mt-1 text-sm text-slate-600">{formatPrice(item.unitPrice)} × {item.qty}</p></div><p className="font-semibold">{formatPrice(item.subtotal)}</p></div>)}</div><div className="mt-4 ml-auto max-w-xs space-y-2 border-t pt-4 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>{formatPrice(subtotal)}</span></div><div className="flex justify-between"><span>VAT</span><span>{formatPrice(po.vatAmount)}</span></div><div className="flex justify-between text-base font-bold"><span>Grand total</span><span>{formatPrice(po.totalAmount)}</span></div></div></section>
  <section className="rounded-xl border border-slate-100 bg-white p-5"><h2 className="font-semibold">{po.rfqs.length ? "Linked RFQs" : "Manual Purchase Order"}</h2>{po.rfqs.length ? <ul className="mt-3 space-y-2">{po.rfqs.map(rfq => <li key={rfq.id} className="rounded-lg bg-slate-50 px-3 py-2 text-sm"><span className="font-medium">{rfq.rfqNumber}</span> · {rfq.status}</li>)}</ul> : <p className="mt-2 text-sm text-slate-600">This purchase order was created directly without an RFQ.</p>}</section>
  <section className="rounded-xl border border-slate-100 bg-white p-5"><h2 className="font-semibold">Delivery</h2><div className="mt-3 grid gap-3 sm:grid-cols-2"><input type="date" value={date} onChange={e => setDate(e.target.value)} className="rounded-lg border p-2 text-sm" /><input value={address} onChange={e => setAddress(e.target.value)} placeholder="Delivery address" className="rounded-lg border p-2 text-sm" /></div><button disabled={busy} onClick={() => action(async () => { await purchaseOrderApi.updateDelivery(po.id, { scheduledDate: date || undefined, address: address || undefined }); return purchaseOrderApi.get(po.id); })} className="mt-3 rounded-lg border px-3 py-2 text-sm font-medium">Save delivery information</button></section>
  <section className="rounded-xl border border-slate-100 bg-white p-5"><div className="flex items-center gap-2"><MessageSquare className="size-5" /><h2 className="font-semibold">Purchase order conversation</h2></div><div className="mt-4 space-y-3">{po.conversation?.messages?.map(msg => <ConversationEventCard key={msg.id} event={{ kind: "message", data: msg }} />) ?? <p className="text-sm text-slate-500">No conversation available.</p>}</div><div className="mt-4 flex gap-2"><input value={message} onChange={e => setMessage(e.target.value)} className="flex-1 rounded-lg border p-2 text-sm" placeholder="Message supplier" /><button disabled={!message.trim() || busy} onClick={async () => { setBusy(true); try { await purchaseOrderApi.sendMessage(po.id, message); setMessage(""); await load(); } finally { setBusy(false); } }} className="rounded-lg bg-[#2f8f83] px-4 text-sm font-medium text-white">Send</button></div></section></div>
  <aside className="space-y-6"><section className="rounded-xl border border-slate-100 bg-white p-5"><h2 className="font-semibold">Actions</h2>{po.status === "PENDING" && <div className="mt-4 space-y-3"><button disabled={busy} onClick={() => action(() => purchaseOrderApi.accept(po.id))} className="flex w-full items-center justify-center gap-2 rounded-lg bg-[#2f8f83] py-2.5 font-medium text-white"><Check className="size-4" />Accept PO</button><textarea value={reason} onChange={e => setReason(e.target.value)} placeholder="Reason for rejection (required)" className="w-full rounded-lg border p-2 text-sm" /><button disabled={busy || !reason.trim()} onClick={() => action(() => purchaseOrderApi.reject(po.id, reason))} className="flex w-full items-center justify-center gap-2 rounded-lg border border-red-200 py-2.5 font-medium text-red-700"><X className="size-4" />Reject PO</button></div>}{po.status === "ACCEPTED" && <div className="mt-4 space-y-3"><select value={method} onChange={e => setMethod(e.target.value as typeof method)} className="w-full rounded-lg border p-2 text-sm"><option value="E_WALLET">E-wallet</option><option value="CARD">Card</option><option value="CASH">Cash</option></select><input value={reference} onChange={e => setReference(e.target.value)} placeholder="Payment reference" className="w-full rounded-lg border p-2 text-sm" /><button disabled={busy} onClick={() => action(() => purchaseOrderApi.preparePayment(po.id, method, reference))} className="w-full rounded-lg bg-[#2f8f83] py-2.5 font-medium text-white">Prepare Payment</button><p className="text-xs text-slate-500">Preparation does not transfer or mark payment as paid.</p></div>}{po.status === "REJECTED" && <p className="mt-3 text-sm text-red-700">Reason: {po.rejectionReason}</p>}</section>
  <section className="rounded-xl border border-slate-100 bg-white p-5"><h2 className="font-semibold">Receipt</h2>{po.receiptSnapshot ? <><button onClick={() => setShowReceipt(!showReceipt)} className="mt-3 rounded-lg border px-3 py-2 text-sm font-medium">{showReceipt ? "Hide Receipt" : "View Receipt"}</button>{showReceipt && <pre className="mt-3 max-h-64 overflow-auto rounded-lg bg-slate-50 p-3 text-xs">{JSON.stringify(po.receiptSnapshot, null, 2)}</pre>}</> : <p className="mt-2 text-sm text-slate-500">No receipt has been sent yet.</p>}<p className="mt-3 text-xs text-slate-500">PDF download is unavailable until the marketplace provides a receipt storage/PDF endpoint.</p></section></aside></div>
 </div></div></div></main></AgentAuthProvider>;
}
