import type { WholesaleProduct, ProductReview } from "@/types/wholesale";

const images = (baseId: string) => [
  `https://images.unsplash.com/${baseId}?auto=format&fit=crop&w=800&q=80`,
  `https://images.unsplash.com/${baseId}?auto=format&fit=crop&w=800&q=80&sig=2`,
  `https://images.unsplash.com/${baseId}?auto=format&fit=crop&w=800&q=80&sig=3`,
  `https://images.unsplash.com/${baseId}?auto=format&fit=crop&w=800&q=80&sig=4`,
];

const sampleReviews: ProductReview[] = [
  {
    id: "rev-1",
    userName: "Juan Dela Cruz",
    rating: 5,
    date: "2024-01-15",
    comment: "Excellent quality cement, consistent strength. Will order again!",
    verified: true,
  },
  {
    id: "rev-2",
    userName: "Maria Santos",
    rating: 4,
    date: "2024-01-10",
    comment: "Good product, fast delivery. MOQ pricing helps our budget.",
    verified: true,
  },
];

export const productDetails: Record<string, WholesaleProduct> = {
  "product-1": {
    id: "product-1",
    name: "Portland Cement Type 1",
    images: images("photo-1518709594023-6eab9bab7b23"),
    supplier: "BuildPro Materials",
    supplierVerified: true,
    supplierLocation: "Cebu City, Philippines",
    supplierResponseTime: "Within 1 hour",
    priceTiers: [
      { minQty: 1, unitPrice: "₱280.00", currency: "PHP" },
      { minQty: 500, unitPrice: "₱265.00", currency: "PHP" },
      { minQty: 1000, unitPrice: "₱255.00", currency: "PHP" },
      { minQty: 5000, unitPrice: "₱245.00", currency: "PHP" },
      { minQty: 10000, unitPrice: "₱235.00", currency: "PHP" },
    ],
    moq: "500 bags",
    sampleAvailable: true,
    samplePrice: "₱280.00",
    leadTime: "3–5 days",
    shippingFrom: "Cebu Port",
    category: "Construction & Building",
    verified: true,
    totalOrders: 15234,
    rating: 4.8,
    attributes: [
      { name: "Grade", value: "Type 1 - General Purpose" },
      { name: "Packaging", value: "50 kg bag" },
      { name: "Strength", value: "4,000 psi (28-day)" },
      { name: "Setting Time", value: "Initial: 45-60 min, Final: 10-12 hours" },
      { name: "Standards", value: "PNS 225:2017" },
      { name: "Storage", value: "Keep dry, stack properly" },
    ],
    customizations: [
      {
        id: "oem-1",
        title: "OEM Branding",
        type: "OEM",
        minimumQuantity: 10000,
        additionalCost: "₱5.00 per bag",
        description: "Custom logo printing on bags",
      },
    ],
    packaging: {
      sellingUnit: "Per bag",
      packageLength: 50,
      packageWidth: 35,
      packageHeight: 15,
      packageWeight: 50,
    },
    shippingInfo: {
      originCountry: "Philippines",
      originProvince: "Cebu",
      originCity: "Cebu City",
      estimatedDays: 5,
      shippingNotes: "Ships via bulk cargo. Proper stacking required.",
    },
    documents: [
      { id: "doc-1", type: "ISO", title: "ISO 9001:2015 Quality Certificate", fileUrl: "#", verified: true },
      { id: "doc-2", type: "OTHER", title: "PNS 225:2017 Compliance", fileUrl: "#", verified: true },
    ],
    supplierCapabilities: [
      { id: "cap-1", name: "OEM/ODM Services", icon: "Factory", available: true, description: "Custom branding available" },
      { id: "cap-2", name: "Sample Provision", icon: "Award", available: true, description: "Samples available for testing" },
      { id: "cap-3", name: "Fast Dispatch", icon: "Truck", available: true, description: "Within 24 hours" },
    ],
    reviews: sampleReviews,
  },
  "product-2": {
    id: "product-2",
    name: "Deformed Steel Bar 16mm",
    images: images("photo-1535813547-7f3f3f8b4a23"),
    supplier: "IronCore Trading",
    supplierVerified: true,
    supplierLocation: "Davao City, Philippines",
    supplierResponseTime: "Within 30 minutes",
    priceTiers: [
      { minQty: 1, unitPrice: "₱42.00", currency: "PHP" },
      { minQty: 1000, unitPrice: "₱38.50", currency: "PHP" },
      { minQty: 5000, unitPrice: "₱36.75", currency: "PHP" },
      { minQty: 10000, unitPrice: "₱35.50", currency: "PHP" },
    ],
    moq: "1 ton",
    sampleAvailable: false,
    leadTime: "7 days",
    shippingFrom: "Davao Port",
    category: "Construction & Building",
    verified: true,
    totalOrders: 8921,
    rating: 4.7,
    attributes: [
      { name: "Diameter", value: "16 mm" },
      { name: "Length", value: "12 meters" },
      { name: "Material", value: "Q235 Steel" },
      { name: "Tensile Strength", value: "470 MPa min" },
      { name: "Yield Strength", value: "250 MPa min" },
      { name: "Standards", value: "PNS 49:2019" },
    ],
    customizations: [],
    packaging: {
      sellingUnit: "Per piece (12m)",
      packageWeight: 120,
    },
    shippingInfo: {
      originCountry: "Philippines",
      originProvince: "Davao del Sur",
      originCity: "Davao City",
      estimatedDays: 7,
    },
    documents: [
      { id: "doc-1", type: "ISO", title: "ISO 9001:2015 Certificate", fileUrl: "#", verified: true },
    ],
    supplierCapabilities: [
      { id: "cap-1", name: "ODM Services", icon: "Factory", available: true, description: "Custom steel profiles" },
      { id: "cap-2", name: "Third-Party Inspection", icon: "Shield", available: true, description: "SGS, BV available" },
    ],
    reviews: [
      {
        id: "rev-2-1",
        userName: "Pedro Santos",
        rating: 5,
        date: "2024-01-18",
        comment: "High quality steel, precise dimensions. Reliable supplier.",
        verified: true,
      },
    ],
  },
  "product-3": {
    id: "product-3",
    name: "Jasmine Rice Premium Grade",
    images: images("photo-1586208958839-06c17cacdf08"),
    supplier: "Nueva Harvest Co.",
    supplierVerified: true,
    supplierLocation: "Nueva Ecija, Philippines",
    supplierResponseTime: "Within 2 hours",
    priceTiers: [
      { minQty: 1, unitPrice: "₱65.00", currency: "PHP" },
      { minQty: 50, unitPrice: "₱55.00", currency: "PHP" },
      { minQty: 100, unitPrice: "₱52.00", currency: "PHP" },
      { minQty: 500, unitPrice: "₱48.00", currency: "PHP" },
      { minQty: 1000, unitPrice: "₱45.00", currency: "PHP" },
    ],
    moq: "50 kg (1 sack)",
    sampleAvailable: true,
    samplePrice: "₱65.00",
    leadTime: "2–4 days",
    shippingFrom: "Nueva Ecija Warehouse",
    category: "Food & Beverages",
    verified: true,
    totalOrders: 25678,
    rating: 4.9,
    attributes: [
      { name: "Grain Length", value: "7-8 mm" },
      { name: "Moisture", value: "14% max" },
      { name: "Broken Grains", value: "5% max" },
      { name: "Chalky Grains", value: "1% max" },
      { name: "Foreign Matter", value: "0.5% max" },
      { name: "Origin", value: "Philippines" },
    ],
    customizations: [],
    packaging: {
      sellingUnit: "Per sack (50kg)",
      packageLength: 60,
      packageWidth: 40,
      packageHeight: 20,
      packageWeight: 51,
    },
    shippingInfo: {
      originCountry: "Philippines",
      originProvince: "Nueva Ecija",
      originCity: "Cabanatuan City",
      estimatedDays: 3,
    },
    documents: [
      { id: "doc-1", type: "FDA", title: "FDA Food Grade Certificate", fileUrl: "#", verified: true },
    ],
    supplierCapabilities: [
      { id: "cap-1", name: "Food Grade Certified", icon: "Shield", available: true, description: "FDA certified facility" },
      { id: "cap-2", name: "Large Volume Supply", icon: "Factory", available: true, description: "Up to 1000 metric tons/month" },
    ],
    reviews: [
      {
        id: "rev-3-1",
        userName: "Rice Trader PH",
        rating: 5,
        date: "2024-01-20",
        comment: "Premium jasmine rice, excellent aroma and taste. Perfect for export.",
        verified: true,
      },
      {
        id: "rev-3-2",
        userName: "Golden Grains Co.",
        rating: 4,
        date: "2024-01-12",
        comment: "Good quality rice, competitive pricing. Will reorder.",
        verified: true,
      },
    ],
  },
  "product-5": {
    id: "product-5",
    name: "Solar Panel 550W",
    images: images("photo-1509391366360-2e959784a276"),
    supplier: "SunGrid Philippines",
    supplierVerified: true,
    supplierLocation: "Bulacan, Philippines",
    supplierResponseTime: "Within 1 hour",
    priceTiers: [
      { minQty: 1, unitPrice: "₱7,200.00", currency: "PHP" },
      { minQty: 10, unitPrice: "₱6,800.00", currency: "PHP" },
      { minQty: 50, unitPrice: "₱6,500.00", currency: "PHP" },
      { minQty: 100, unitPrice: "₱6,200.00", currency: "PHP" },
    ],
    moq: "10 pcs",
    sampleAvailable: true,
    samplePrice: "₱7,200.00",
    leadTime: "10 days",
    shippingFrom: "Bulacan Warehouse",
    category: "Electronics",
    verified: true,
    totalOrders: 1245,
    rating: 4.6,
    attributes: [
      { name: "Power Output", value: "550W" },
      { name: "Cell Type", value: "Monocrystalline PERC" },
      { name: "Efficiency", value: "21.5%" },
      { name: "Dimensions", value: "2256 × 1134 × 35 mm" },
      { name: "Weight", value: "28 kg" },
      { name: "Warranty", value: "25 years linear power" },
    ],
    customizations: [
      {
        id: "oem-5-1",
        title: "OEM Packaging",
        type: "PACKAGING",
        minimumQuantity: 100,
        description: "Custom box with buyer branding",
      },
      {
        id: "oem-5-2",
        title: "Power Customization",
        type: "ODM",
        minimumQuantity: 50,
        additionalCost: "₱500.00 per unit",
        description: "Adjust power output to specific needs",
      },
    ],
    packaging: {
      sellingUnit: "Per panel (individual)",
      packageLength: 230,
      packageWidth: 115,
      packageHeight: 40,
      packageWeight: 28,
    },
    shippingInfo: {
      originCountry: "Philippines",
      originProvince: "Bulacan",
      originCity: "Malolos City",
      estimatedDays: 10,
      shippingNotes: "Fragile item - handle with care",
    },
    documents: [
      { id: "doc-1", type: "CE", title: "CE Marking Certificate", fileUrl: "#", verified: true },
      { id: "doc-2", type: "RoHS", title: "RoHS Compliance", fileUrl: "#", verified: true },
      { id: "doc-3", type: "ISO", title: "ISO 14001:2015 Environmental", fileUrl: "#", verified: true },
    ],
    supplierCapabilities: [
      { id: "cap-1", name: "Renewable Energy Certified", icon: "Shield", available: true, description: "CE, RoHS, ISO certified" },
      { id: "cap-2", name: "Custom Solar Solutions", icon: "Factory", available: true, description: "ODM solar panel customization" },
    ],
    reviews: [
      {
        id: "rev-5-1",
        userName: "SolarTech Solutions",
        rating: 5,
        date: "2024-01-22",
        comment: "High efficiency panels, excellent warranty support. Perfect for our solar projects.",
        verified: true,
      },
      {
        id: "rev-5-2",
        userName: "EcoEnergy PH",
        rating: 4,
        date: "2024-01-15",
        comment: "Good panels, reliable supplier. MOQ pricing is competitive.",
        verified: true,
      },
    ],
  },
};