import type { WholesaleProduct, ProductPriceTier } from "@/types/wholesale";

export type { WholesaleProduct };

const image = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=640&q=80`;

// Helper to create price tiers
const priceTiers = (prices: { qty: number; price: string }[]): ProductPriceTier[] =>
  prices.map((p) => ({ minQty: p.qty, unitPrice: p.price, currency: "PHP" }));

// Product listing data - includes required fields for both list and detail views
export const products: WholesaleProduct[] = [
  {
    id: "product-1",
    name: "Portland Cement Type 1",
    image: image("photo-1518709594023-6eab9bab7b23"),
    images: [image("photo-1518709594023-6eab9bab7b23")],
    supplier: "BuildPro Materials",
    supplierVerified: true,
    supplierLocation: "Cebu City, Philippines",
    supplierResponseTime: "Within 1 hour",
    priceTiers: priceTiers([
      { qty: 1, price: "₱280.00" },
      { qty: 500, price: "₱265.00" },
      { qty: 1000, price: "₱255.00" },
      { qty: 5000, price: "₱245.00" },
      { qty: 10000, price: "₱235.00" },
    ]),
    price: "₱265.00",
    unit: "bag",
    moq: "500 bags",
    sampleAvailable: true,
    samplePrice: "₱280.00",
    leadTime: "3–5 days",
    shippingFrom: "Cebu Port",
    location: "Cebu City",
    category: "Construction & Building",
    verified: true,
    totalOrders: 15234,
    rating: 4.8,
    attributes: [
      { name: "Grade", value: "Type 1 - General Purpose" },
      { name: "Packaging", value: "50 kg bag" },
      { name: "Strength", value: "4,000 psi (28-day)" },
    ],
    customizations: [{ id: "oem-1", title: "OEM Branding", type: "OEM", minimumQuantity: 10000, additionalCost: "₱5.00 per bag" }],
  },
  {
    id: "product-2",
    name: "Deformed Steel Bar 16mm",
    image: image("photo-1535813547-7f3f3f8b4a23"),
    images: [image("photo-1535813547-7f3f3f8b4a23")],
    supplier: "IronCore Trading",
    supplierVerified: true,
    supplierLocation: "Davao City, Philippines",
    supplierResponseTime: "Within 30 minutes",
    priceTiers: priceTiers([
      { qty: 1, price: "₱42.00" },
      { qty: 1000, price: "₱38.50" },
      { qty: 5000, price: "₱36.75" },
      { qty: 10000, price: "₱35.50" },
    ]),
    price: "₱38.50",
    unit: "kg",
    moq: "1 ton",
    sampleAvailable: false,
    leadTime: "7 days",
    shippingFrom: "Davao Port",
    location: "Davao City",
    category: "Construction & Building",
    verified: true,
    totalOrders: 8921,
    rating: 4.7,
    attributes: [
      { name: "Diameter", value: "16 mm" },
      { name: "Length", value: "12 meters" },
      { name: "Material", value: "Q235 Steel" },
    ],
    customizations: [],
  },
  {
    id: "product-3",
    name: "Jasmine Rice Premium Grade",
    image: image("photo-1586208958839-06c17cacdf08"),
    images: [image("photo-1586208958839-06c17cacdf08")],
    supplier: "Nueva Harvest Co.",
    supplierVerified: true,
    supplierLocation: "Nueva Ecija, Philippines",
    supplierResponseTime: "Within 2 hours",
    priceTiers: priceTiers([
      { qty: 1, price: "₱65.00" },
      { qty: 50, price: "₱55.00" },
      { qty: 100, price: "₱52.00" },
      { qty: 500, price: "₱48.00" },
      { qty: 1000, price: "₱45.00" },
    ]),
    price: "₱55.00",
    unit: "kg",
    moq: "50 kg (1 sack)",
    sampleAvailable: true,
    samplePrice: "₱65.00",
    leadTime: "2–4 days",
    shippingFrom: "Nueva Ecija Warehouse",
    location: "Nueva Ecija",
    category: "Food & Beverages",
    verified: true,
    totalOrders: 25678,
    rating: 4.9,
    attributes: [
      { name: "Grain Length", value: "7-8 mm" },
      { name: "Moisture", value: "14% max" },
    ],
    customizations: [],
  },
  {
    id: "product-5",
    name: "Solar Panel 550W",
    image: image("photo-1509391366360-2e959784a276"),
    images: [image("photo-1509391366360-2e959784a276")],
    supplier: "SunGrid Philippines",
    supplierVerified: true,
    supplierLocation: "Bulacan, Philippines",
    supplierResponseTime: "Within 1 hour",
    priceTiers: priceTiers([
      { qty: 1, price: "₱7,200.00" },
      { qty: 10, price: "₱6,800.00" },
      { qty: 50, price: "₱6,500.00" },
      { qty: 100, price: "₱6,200.00" },
    ]),
    price: "₱6,800.00",
    unit: "pc",
    moq: "10 pcs",
    sampleAvailable: true,
    samplePrice: "₱7,200.00",
    leadTime: "10 days",
    shippingFrom: "Bulacan Warehouse",
    location: "Bulacan",
    category: "Electronics",
    verified: true,
    totalOrders: 1245,
    rating: 4.6,
    attributes: [
      { name: "Power Output", value: "550W" },
      { name: "Cell Type", value: "Monocrystalline PERC" },
      { name: "Efficiency", value: "21.5%" },
    ],
    customizations: [
      { id: "oem-5-1", title: "OEM Packaging", type: "PACKAGING", minimumQuantity: 100, description: "Custom box with buyer branding" },
      { id: "oem-5-2", title: "Power Customization", type: "ODM", minimumQuantity: 50, additionalCost: "₱500.00 per unit" },
    ],
  },
];